### ISSUE TITLE
Documentation page returns error 

### ISSUE THREAD

**Issue by vbalaji21** [yale-sean/social_sim_ros#3]
Hi,

The documentation page you mentioned returns an error - https://github.com/yale-sean/docs

**Comment by MLotfy96** [comment]
Hello,

I think the documentation has been moved to this website: [https://sean.interactive-machines.com/](https://sean.interactive-machines.com/)

**Comment by vbalaji21** [comment]
@MLotfy96 Thank you. I have 2 questions and I have mentioned it below.

I would like to get answers for these questions -
1) Information explaining how SEAN metrics are calculated, any paper information or formula will be good? I saw all the SEAN metrics here https://sean.interactive-machines.com/docs/metrics/

2) Is this the only paper for SEAN https://arxiv.org/pdf/2009.04300.pdf or any more papers are there, can you please refer me the links ?

**Comment by vbalaji21** [comment]
@MLotfy96, @nathantsoi, @marynelv, @JCespi Can you please let me know any information explaining how SEAN metrics are calculated, any paper information or formula will be good?

**Comment by nathantsoi** [comment]
Hi @vbalaji21 , please see https://sean.interactive-machines.com/docs/metrics

Feel free to email me if you need anything else: nathan.tsoi@yale.edu

**Comment by vbalaji21** [comment]
@nathantsoi I saw the metrics on your website but I want to know how the metrics are calculated, any paper describing the formula for metrics be good. I am a graduate Master's student, I need this information to write and submit it to my professor, please help me out.

**Comment by nathantsoi** [comment]
The metrics are computed here: https://github.com/yale-sean/social_sim_unity/blob/main/Assets/Scripts/SEAN/Metrics/Metrics.cs
